# Generated by Django 2.1.3 on 2018-11-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='fundation',
        ),
    ]
