# Generated by Django 2.1.3 on 2018-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_developer_fundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pic',
            field=models.ImageField(default='Imagem não disponível', upload_to='media/'),
            preserve_default=False,
        ),
    ]
