# Generated by Django 2.1.3 on 2018-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(default=0),
        ),
    ]
