# Generated by Django 2.1.3 on 2018-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_metacritic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
