# Generated by Django 2.1.3 on 2018-11-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('game', '0005_game_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamesInformation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('currently_playing', models.ManyToManyField(related_name='currently_playing', to='game.Game')),
                ('finished', models.ManyToManyField(related_name='finished', to='game.Game')),
                ('want_to_play', models.ManyToManyField(related_name='want_to_play', to='game.Game')),
            ],
        ),
    ]
