# Generated by Django 2.1.3 on 2018-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20181118_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pic',
        ),
        migrations.AddField(
            model_name='game',
            name='pic1',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='game',
            name='pic2',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='game',
            name='pic3',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
