# Generated by Django 2.1.3 on 2018-11-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20181119_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pic1',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pic2',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pic3',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
