# Generated by Django 2.1.3 on 2018-11-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
