# Generated by Django 2.1.3 on 2018-11-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
