# Generated by Django 2.1.3 on 2018-11-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20181121_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Playing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='currently_playing',
            field=models.ManyToManyField(blank=True, related_name='currently_playing', to='game.Playing'),
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='finished',
            field=models.ManyToManyField(blank=True, related_name='finished', to='game.Finished'),
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='want_to_play',
            field=models.ManyToManyField(blank=True, related_name='want_to_play', to='game.Wishlist'),
        ),
    ]
