# Generated by Django 2.1.3 on 2018-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20181123_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playing',
            name='game',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='game',
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='currently_playing',
            field=models.ManyToManyField(blank=True, null=True, related_name='currently_playing', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='finished',
            field=models.ManyToManyField(blank=True, null=True, related_name='finished', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='want_to_play',
            field=models.ManyToManyField(blank=True, null=True, related_name='want_to_play', to='game.Game'),
        ),
        migrations.DeleteModel(
            name='Finished',
        ),
        migrations.DeleteModel(
            name='Playing',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
