# Generated by Django 2.1.3 on 2018-11-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20181129_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamesinformation',
            name='currently_playing',
            field=models.ManyToManyField(blank=True, related_name='currently_playing', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='finished',
            field=models.ManyToManyField(blank=True, related_name='finished', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='usergamesinformation',
            name='want_to_play',
            field=models.ManyToManyField(blank=True, related_name='want_to_play', to='game.Game'),
        ),
    ]
